image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      python -m pip install --upgrade pip
      python -m pip install Django
      python -m pip install --upgrade Pillow
      python -m pip install django-imagekit
      python -m pip install boto3
      python -m pip install django-storages
      python -m pip install pylibdmtx 
      python -m pip install pylibdmtx[scripts]
      python -m pip install fpdf2
      python manage.py migrate
      npm install && npm run build
      npm install axios
    command: |
      python manage.py runserver
      npm run dev
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
