image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      python -m pip install --upgrade pip
      python -m pip install Django
      python -m pip install --upgrade Pillow
      python -m pip install django-imagekit
      python -m pip install boto3
      python -m pip install django-storages
      python -m pip install pylibdmtx 
      python -m pip install pylibdmtx[scripts]
      python -m pip install fpdf2
      python -m pip install numpy
      python -m pip install opencv-python-headless
      python -m pip install django-taggit
      python -m pip install djangorestframework
      python -m pip install markdown
      python -m pip install django-filter
      python manage.py migrate
      npm install axios
    command: |
      python manage.py runserver
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
