# Generated by Django 3.2.4 on 2021-07-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('attributes', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value_type', models.IntegerField(choices=[(1, 'String'), (2, 'Number')])),
            ],
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='uid_text',
            new_name='uid',
        ),
    ]
