# Generated by Django 3.2.4 on 2021-07-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20210729_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
