# Generated by Django 3.2.4 on 2021-08-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_auto_20210801_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
