# Generated by Django 3.2.4 on 2021-08-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_alter_attribute_value_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='short_name',
            field=models.CharField(default='replace it', max_length=10),
        ),
    ]
