# Generated by Django 3.2.4 on 2021-08-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_attribute_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='short_name',
            field=models.CharField(default='replace it', max_length=10, unique=True),
        ),
    ]
