# Generated by Django 3.2.4 on 2021-08-02 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0008_alter_attribute_short_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='plant',
            managers=[
                ('logs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='action time')),
                ('action_type', models.IntegerField(choices=[(1, 'Addition'), (2, 'Change'), (3, 'Deletion')])),
                ('data', models.JSONField()),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
