# Generated by Django 3.2.6 on 2021-08-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0012_alter_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='access_type',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Friends'), (2, 'Private')], default=0),
        ),
    ]
