# Generated by Django 3.2.6 on 2021-08-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0013_plant_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='show_in_list',
            field=models.BooleanField(default=True),
        ),
    ]
