# Generated by Django 3.2.6 on 2021-08-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0014_attribute_show_in_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='filterable',
            field=models.BooleanField(default=False),
        ),
    ]
