# Generated by Django 3.2.6 on 2021-08-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0016_auto_20210827_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='value_type',
            field=models.IntegerField(choices=[(1, 'String'), (2, 'Number'), (3, 'Text'), (4, 'Date'), (5, 'Textarea')]),
        ),
    ]
