# Generated by Django 3.2.6 on 2021-08-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0017_alter_attribute_value_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='attributes',
        ),
        migrations.AddField(
            model_name='action',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='action',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='RichPlant',
        ),
    ]
