# Generated by Django 3.2.6 on 2021-08-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0018_auto_20210831_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='related_attributes',
            field=models.ManyToManyField(blank=True, to='plants.Attribute'),
        ),
    ]
