# Generated by Django 3.2.6 on 2021-08-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0019_action_related_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='comment_option',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_type',
            field=models.IntegerField(choices=[(1, 'String'), (2, 'Number'), (4, 'Date'), (5, 'Textarea')]),
        ),
    ]
