# Generated by Django 3.2.7 on 2021-09-16 14:22

from django.db import migrations, models
import plants.models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0022_alter_photo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=plants.models.user_directory_path),
        ),
    ]
