# Generated by Django 3.2.7 on 2021-09-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0023_alter_photo_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='original',
        ),
    ]
