# Generated by Django 3.2.7 on 2021-09-16 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0024_rename_photo_photo_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='plant',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='plants.plant'),
            preserve_default=False,
        ),
    ]
