# Generated by Django 3.2.7 on 2021-09-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0025_photo_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='plant',
        ),
    ]
