# Generated by Django 3.2.7 on 2021-09-16 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0026_remove_photo_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.plant'),
        ),
    ]
