# Generated by Django 3.2.7 on 2021-09-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0027_photo_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='profile_photo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='plants.photo'),
        ),
    ]
