# Generated by Django 3.2.4 on 2021-08-01 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_alter_attribute_value_type'),
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.plant'),
        ),
    ]
